language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

services:
    - mongodb

env:
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=3.1.*
    - SYMFONY_VERSION=3.2.*

before_script:
    - phpenv config-add travis-php.ini
    - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then echo 'extension = "mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis-php.ini; fi;
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then echo 'extension = "mongodb.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis-php.ini; fi;
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/form:${SYMFONY_VERSION} --no-update
    - composer update

script:
    - phpunit
